### ISSUE TITLE
Константа вместо аргумента функции

### ISSUE THREAD

**Issue by mrdimfox** [weithhh/PhasyTorn#1]
[Вот тут](https://github.com/weithhh/PhasyTorn/blob/e8b26a3e3cb40c4aa58ad9dcd8ac6291c9b1ac6c/Src/main.c#L119) вместо агрумента `samples_count` используется дефайн `SAMPLES_COUNT`.

**Comment by weithhh** [comment]
Отделил код генератора синусоиды от main.c в https://github.com/weithhh/PhasyTorn/commit/7d52aea474259216e3135cede2dc081837a58bfc
