### ISSUE TITLE
Возможное зависание в sleep

### ISSUE THREAD

**Issue by mrdimfox** [weithhh/PhasyTorn#2]
https://github.com/weithhh/PhasyTorn/blob/e8b26a3e3cb40c4aa58ad9dcd8ac6291c9b1ac6c/Src/main.c#L23

https://github.com/weithhh/PhasyTorn/blob/e8b26a3e3cb40c4aa58ad9dcd8ac6291c9b1ac6c/Src/main.c#L197

При такой реализации `sleep` существует вероятность, что произойдёт переполнение `systick_delay` и зависание в цикле `while`. Такая ситуация может произойти при наличии любых других прерываний, отличных от systick.

Например в следующей ситуации:
1. Вход в функцию `sleep` с параметром `usec=2`.
2. Попадание в долгое прерывание > 2 us с приоритетом ниже systick.
3. Во время долгого прерывания `systick_delay` переполняется (становится меньше 0), так как прерывание systick будет вызвано более 2 раз.
4. Выход из долгого прерывания и возврат к основному потоку (к функции `sleep`).
5. Зависание в цикле `while` так как `systick_delay` становится равным ~2^32.

**Comment by weithhh** [comment]
Исправил в https://github.com/weithhh/PhasyTorn/commit/28cde2b439fb694feceb1743064c41e62c3b03ec
